---
title: "参考文献介绍"
author:
  - 李宇
documentclass: ctexart
output:
pdf_document: 
    toc: yes
    latex_engine: "xelatex"
    extra_dependencies:
      ctexcap: UTF8
---
### 文献
金启轩.中国新冠肺炎疫情预测建模与理性评估[J].统计与决策

## 一 数据说明
这篇文章以2020年1月23日武汉“封城”为初始节点，对2020/1/23至 2020/2/12 的全国除湖北外的30省份数据进行分析。选取30个省份的数据是因为疫情前期湖北省的确诊人数仅仅反映了核酸的检测能力，并非是真实的疫情情况，为了综合整个国家对疫情的处置，预测比较符合实际的疫情发展状况，所以剔除了湖北省的数据，从而为疫情处理提供有价值的参考, 消除民众的恐慌心理。

## 二 主要思想
先做一个初步判断：在1月23日之后，疫情的有效传播率极大概率是小于1的，即在传播学上该疫情是处于被控制的状态而非处于爆发扩张状态。后面的内容是去证明这个判断，对数据进行统计和建模，从而估算1月23日的感染数及分布，以及1月23日前一周开始的各个阶段有效传播率，进而评估疫情的发展规模：结束时间及疫情人数。
在模型建立中，主要做了两方面的工作：一是对增长率进行了建模，另一个是对每日新增确诊人数进行了建模。并由此将内容分为了全国 30 省份疫情的性质和全国 30 省份疫情的规模两部分。

## 三 主要工作

### 1.全国 30 省份疫情的性质
从增长率的发展趋势来看，自1月28日起，确诊人数的增长率呈较为规律的线性下降趋势。因此文章选取1月28日为第1天，对从 2020/1/28至 2020/2/12 的数据进行分析。
 
#### ①线性回归
文中的增长率图显示：第 8 天后的增长率变化趋势与前8天的显然不同，所以选了第8天(2月4日)以后的数据进行拟合，天数记为 t，做了线性回归，得到的方程是：增长率=15.37%-0.84%t，拟合优度 R²为 96%。令增长率为 0，可得 t=18（天），结果表明全国30省确诊日增长率大概率在2月21日左右趋近于0。

#### ②时间序列中的 3 日加权平均移动法
为提高拟合度，对增长率做了3 日加权平均移动法的处理，再次进行最小二乘法估计得到方程：增长率=20.00-1.10%t，这一次的模型拟合优度 R²为 98%，高度拟合。再令增长率为 0，可得 t=18（天），结果表明全国30省份确诊日增长率大概率在 2 月 19 日左右趋近于 0。
文献中，日增长率以 y=kx+b 的形式可实现高度拟合，k值可理解为国家和整个社会对于病毒的防控力度。防控力度越大，k 的绝对值越大（负值更大），直线会更快地达到 0 点，即确诊人数会更快达到峰值。

### 2.全国 30 省份疫情的规模

#### ①每日新增确诊人数的变化
考虑到在全国 30 省份内人传人主要是二代病例，三代病例较少，四代较为罕见，文章对全国 30 省份日增确诊数用分别用一次和二次函数进行分段拟合处理。
一次函数：日增确诊人数=-59t+1235.5，拟合优度R²为95.90%，天数≈21 时，全国 30 省份新增确诊人数趋于0。 
二次函数：日增确诊人数=3.7t²-151.9t+1796.3（无零点），拟合优度R²为 97.42%，数据有可能更符合此二次模型变化趋势。计算其最低点：天数=21。
综合分析结果得：全国 30 省份每日新增确诊人数可能于第21天（2月17 日）趋近于0，此时全国 30 省总确诊人数可能趋近于顶峰。
文献用一次和二次多项式实现高度拟合，表明本次疫情全国 30 省份确诊病例主要是二代感染者，而二次拟合的拟合度高于一次拟合，说明存在三代及以上感染者，但占比较少。这也可以说明我国在阻止疫情传播方面非常成功，有效地阻断了病毒的多代传播。

#### ②原始基数和有效传播率估算
主要是用北京、天津、上海、辽宁、陕西和江苏六个省份的数据作为样本，去估算全国30省份的本地传染者。从病例分布的统计数据中发现，截止2月3日，六省份共1006个确诊中本地感染者约有329 个，即本地传染占比约 33%。以此为样本估算全国 30 省份的本地传染者，约有2418 人，从而可以计算1 月 23日全国30省份的初始基数约为 7354-2418=4896。（初始基数指各省的输入病例之和）。但实际情况是直到2月6日，依然存在确诊的输入病例，因此该原始基数的值应略大于 4896 的5%,即在 4896-5150 人之间。
根据前面拟合的日增长确诊人数函数，估算本次疫情全国 30 省份的总感染 数是小于 14000 的，2 月17日前后确诊病例可能不会再大幅增长。文章还估算了1月23日前一周开始的各个阶段有效传播率，认为８日周期等价有效传播率不大于 0.62，4 日周期等价有效传播率不大于0.31。传播率低说明我国政府和人民投入巨大的人力物力所取得的效果是极其出色的。

## 四 总结
这篇文献用了通俗易懂的统计学模型来说明疫情的性质和规模，对我们做的工作有一定的参考价值。但文献截稿日期较早，使用的数据比较少，对疫情结束日期的预测有所偏差，这是其中的一点不足之处。

