---
title: "意大利新冠肺炎疫情预测建模与理性评估"
author: "戎翔 高彦梅 李宇 卫晓帆"
date: "2020/4/1"
output:  
  html_document: default
  pdf_document: default
geometry: lmargin=2.5cm rmargin=2.5cm
fontsize: 12pt
doumentclass: article
---


## 一、意大利疫情背景信息
### （1）意大利基本情况
#######
意大利是发达工业国，欧洲第四大、世界第八大经济体。中小企业发达，被誉为“中小企业王国”，中小企业数量占企业总数的98%以上。地区经济发展不平衡，北方工商业发达，南方以农业为主，经济较为落后。  
工业：实体经济发达，是欧盟内仅次于德国的第二大制造业强国。  
旅游业：旅游业发达，是世界第五大旅游国。主要旅游城市包括罗马、威尼斯、佛罗伦萨等。旅游从业人员约32万人。  
对外贸易：对外贸易是意经济的主要支柱。外贸产值占国内生产总值40%以上。个人消费品、机械设备以及服务在国际市场占据非常重要的地位。意大利产品在国际上有较强竞争力，出口商品种类非常齐全。  

### （2）疫情发展
#######
意大利是最早一批与中国取消直航的国家，随着疫情的快速蔓延，意大利防疫措施进一步收紧。   1月21日，世界卫生组织和欧洲疾病预防控制中心认为，病毒传入欧盟的可能性很小。  
1月23日，开始对来自武汉的飞机乘客测量体温，并进行行程登记。  
1月30日，暂停所有往来中国的航班。  
1月31日，总统宣布国家进入紧急状态，并拨出款项应对新冠肺炎疫情。  
2月6日，对近期去过武汉的意大利人实施隔离。  
2月23日，12个市镇被封锁，超过5万人被强制要求在家进行自我隔离。  
3月4日，意大利新冠肺炎累计确诊3089例。意大利紧急取消一年一度的威尼斯狂欢节，多个城市停课、意大利式“火神山医院”正在建设 ，多地物流暂停。                                    
3月9日，意大利总理孔特宣布，10日起对全国进行“封锁”。这意味着意大利6000多万人的流动将受到限制。所有的公共集会都将被禁止，电影院、剧院等娱乐场所也将关闭，葬礼、婚礼和体育赛事都将暂停。意大利成为中国外新冠肺炎疫情最严重的国家。  
3月12日，意大利紧急向迈瑞医疗采购首批近万台抗疫设备，主要为监护仪等产品。  
3月27日，意大利国防部宣布撤回200名驻伊士兵，只保留必要的设施和力量。  
3月29日，意大利成为新冠肺炎病亡人数最多的国家。  
3月31日，意大利累计新冠肺炎确诊病例超过十万例。     

### （3）意大利疫情爆发迅速的原因
#######
1.早期没有认识到问题的严重性，没有采取严防输入的措施，多为第二代传染，潜伏周期也相应地延长；  
2.三月后，逐渐出现大爆发势头，后期的检测和隔离措施没有跟上；  
3.与国情有关。意大利人崇尚自由，初期没有认识到问题的严重性，出门不戴口罩、公园散步、参加体育赛事等。  

### （4）新冠肺炎疫情对意大利的影响
#######
1.经济有可能出现衰退。自2008年金融危机以来，意大利经济持续低迷。受国内政局不稳、全球贸易摩擦和欧盟贸易需求低迷等因素的影响，2019年第四季度意大利经济环比收缩0.3%，为六年来最大降幅，全年增速估计值为0.2%。受此次疫情影响最为严重的伦巴第和威尼托两个大区，是意大利的工业和金融中心，两个大区GDP占意大利GDP的比例接近三分之一。如果局势不能迅速缓解，意大利今年GDP或将收缩超过1%。  
2.机械设备和旅游业受影响较为严重。意大利经济的贸易依赖度较高，2018年商品和服务出口占GDP的31%。机械设备是其最主要的贸易产品，机械设备盈余对其货物贸易盈余的贡献度超过130%。意大利机械设备制造主要集中于受疫情影响较严重的威尼托地区，北部地区封闭隔离将对机械设备制造业造成较严重的打击。此外，意大利是世界第五大旅游目的地，旅游业对GDP的贡献率约为13%，对经常账户顺差的贡献率超过35%。此次疫情导致旅游业遭受重创，大量景点关门，餐馆缩短营业，取消酒店预订的情况较为普遍。  

